export const sharing = [
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
  {
    id: 1,
    title: "아이팜 센서는 체계적인 것 같네요",
    user: "유진",
    date: "2024.08.25",
    comments: 5,
  },
];
