name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the project
        run: npm install && npm run build

      - name: Trigger Netlify Build
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/66f6216de1063baa9374f7c5
